### PR TITLE
 Update ISO 639 and autonym table

### PR DESCRIPTION
**Pull request by NullVerdict**
This PR updates the ISO 639 and autonym table using RFC 5646. RFC 5646 defines a standard format for identifying languages and regional variants. This allows for more accurate and universal labeling of languages and avoids confusion or inconsistency. In this PR, I added new language codes and autonyms, and corrected some errors and outdated data in the existing table.

### CODE REVIEW

**Comment by NullVerdict** [comment]
I noticed repetitions in the tables, I'll fix it later

**Comment by NullVerdict** [comment]
If the key is repeated twice, everything breaks. See what the problem is. I'm sure that's right.

**Comment by NullVerdict** [comment]
Can you fix the error in tests?

**Comment by humenda** [comment]
Sorry for being so late on this. Would you please rebase your changes on latest
master? Also, would you please, just for safety, link the sources from which you
got the tables from? The same as referenced in the README?

Thanks!

**Comment by NullVerdict** [comment]
Updated, I got the tables from [here](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)

**Comment by humenda** [comment]
Thanks!

**Comment by aumetra** [comment]
How exactly did you generate these tables? Because it seems like a manual conversion, and that you seem to have added the "macrolanguage" field as the two-letter code.

This not only doesn't seem quite correct, it also breaks the codegen since it operates under the assumption that each language has a unique code (hence the failed CI runs)

**Comment by NullVerdict** [comment]
> How exactly did you generate these tables? Because it seems like a manual conversion, and that you seem to have added the "macrolanguage" field as the two-letter code.
> 
> This not only doesn't seem quite correct, it also breaks the codegen since it operates under the assumption that each language has a unique code (hence the failed CI runs)

I converted the tables to JSON, then added the necessary data and converted to table format again. This seems to be a violation of RFC 5646, which allows duplicate language codes. Try to fix it :/

**Comment by aumetra** [comment]
> I converted the tables to JSON, then added the necessary data and converted to table format again

I think having the script you used for that (if you used one) would be pretty neat, simply so that future contributors trying to update the tables have an easier time reproducing the same results

**Comment by NullVerdict** [comment]
> > I converted the tables to JSON, then added the necessary data and converted to table format again
> 
> I think having the script you used for that (if you used one) would be pretty neat, simply so that future contributors trying to update the tables have an easier time reproducing the same results

I had 2 scripts converting language-subtag-registry to json and gluing the two files by parameters. I converted tab and tsv to json via sites (to make it easier)

**Comment by humenda** [comment]
Please be so kind to provide importer scripts in a PR. Since the merge, the CI
fails so I would need to revert the change otherwise. Thanks

**Comment by NullVerdict** [comment]
> Please be so kind to provide importer scripts in a PR. Since the merge, the CI fails so I would need to revert the change otherwise. Thanks

What do you mean? I only mean scripts for sorting values and gluing files together. These scripts can be done in 30 minutes.

**Comment by humenda** [comment]
Sure. However, before your change, the contents could be downloaded without
scripts. To keep the maintenance effort low, it would be nice if there were a
script to update the tables. I would prefer to not reverse-engineer this.

**Pull request merged**
