### PR TITLE
Support lowercase str for Language::from_xxx.

### PR DESCRIPTION
**Pull request by zensh**
In practical usage scenarios, the input name may be in lowercase format instead of standard name, it is very practical.

### CODE REVIEW

**Comment by djc** [comment]
Presumably this might be a substantial memory usage increase? Worth checking, and perhaps making this optional with a Cargo feature?

**Comment by humenda** [comment]
Thanks for your PR!

I like the way you did the changes, except for reformatting the keywords in
Cargo.toml, could you undo this?

What is your justification to embed the lower-case version in the binary? String
comparison is a rather fast operation. What about preserving your API, but
moving the checks to run-time, instead of generating the lower-case pendants at
compile-time? I would imagine that we still feature-gate it to protect users
that don't want to have the "double comparison"-penalty. However, since we're
using a hash table here, it might all be sufficiently fast. Do you agree?

**Comment by zensh** [comment]
The `lowercase_names` feature complicates the `impl FromStr for Language` combinations. What if we repurpose `english_names`, add a `from_name_lowercase` method, and enhance the `from_str` method?

We might need a Makefile to run `cargo clippy` and `cargo test` across all feature combinations for developing. 😀

```sh
.PHONY: lint test

lint:
	@cargo clippy --no-default-features
	@cargo clippy --all-features
	@cargo clippy --no-default-features --features=english_names
	@cargo clippy --no-default-features --features=lowercase_names
	@cargo clippy --no-default-features --features=local_names
	@cargo clippy --no-default-features --features=english_names,lowercase_names
	@cargo clippy --no-default-features --features=local_names,lowercase_names
	@cargo clippy --no-default-features --features=local_names,english_names
	@cargo clippy --no-default-features --features=english_names,lowercase_names,local_names

test:
	@cargo test --no-default-features
	@cargo test --all-features
	@cargo test --no-default-features --features=english_names
	@cargo test --no-default-features --features=lowercase_names
	@cargo test --no-default-features --features=local_names
	@cargo test --no-default-features --features=english_names,lowercase_names
	@cargo test --no-default-features --features=local_names,lowercase_names
	@cargo test --no-default-features --features=local_names,english_names
	@cargo test --no-default-features --features=english_names,lowercase_names,local_names
```

**Comment by humenda** [comment]
What do you mean by "enhancing" `from_str`? I would propose to have a
`from_str` like it was before (upper case, exact match), `from_str_lowercase`
as an addition. Why would we want to have `from_str` not to be available if
`English_names`? If you go for the proposal of mine, I will merge it as soon
as you have done it.

Regarding the makefile: would you open another PR for this, once this one is
done?

Thanks

**Comment by zensh** [comment]
Agree with you.

**Comment by humenda** [comment]
Where do the changes in the *.tab and *.csv files stem from?

**Comment by humenda** [comment]
Thanks again for the work!

**Pull request merged**
