### PR TITLE
implement PartialOrd and OrdOrdering

### PR DESCRIPTION
**Pull request by ririsoft**
Hello,

Would you consider merging this PR which adds `PartialOrd` and `Ord` to `Language`, following the enum ordering (alphabetical ordering), please ?

Thank you very much in advance !

### CODE REVIEW

**Comment by humenda** [comment]
Hi

Thanks for the PR!

**Comment by ririsoft** [comment]
Thanks a lot !

**Comment by tim-harding** [comment]
This is a pretty useful feature. I noticed that this feature has not made it to the crates.io version. Is there any plan for getting version 2.0.0 to crates.io?

**Comment by humenda** [comment]
I have been waiting for users to test the library, though feedback has been
sparse :). The biggest change is the drop of Diesel support as I am not using
it and its support was broken. I was waiting if somebody would come along and
complain. If you can test it with your application  or use-case, I'll make a
version.

**Comment by tim-harding** [comment]
I [switched](https://github.com/tim-harding/kanjidic_utilities/blob/477537ec0074d1665017cd2880698cb282fc3eed/kanjidic_parser/Cargo.toml#L11) to the Github version of this repository yesterday for my Kanjidic project. So far I haven't had any trouble with it. I can ping you once the project is close to wrapping up if you'd like.

**Pull request merged**
