### PR TITLE
Move build step into an integration test

### PR DESCRIPTION
**Pull request by djc**
Replace the build script with an integration test that fails if the
generated code is out of date. This has several advantages:

* No need for downstream users to compile the build dependencies
* No need for downstream users to compile the build script
* No need for downstream users to run the code generation step
* The generated code is more usable in an IDE
* CI will fail if the generated code is out of date

The main downside is probably that the generated code is kept in
the repository, but this seems of relatively minimal impact,
especially if the code generator/source files don't change often.

### CODE REVIEW

**Comment by humenda** [comment]
- Please document `struct Info`.
- Should the generation really be an integration test? What is the advantage over invoking it ourselves?
- If we keep it as a test, please rename to `tests/generate_static_table.rs` or similar.
- - Please add documentation to the structs, not to the ?`impl` blocks (if that's an old habbit, never mind)

**Comment by djc** [comment]
I've renamed `Info` to `LanguageData` and added quite a bit of documentation and renamed the test file as you suggested. In my mind, the benefit of an integration test is that running the tests will notice that the generated code is out of date, so you're bound to notice. This is a pre-existing pattern that I've seen used in the semver-parser crate and it seems pretty nice to me.

Not quite sure what you meant about documenting `struct` definitions over `impl` blocks, as far as I can tell I didn't really make any changes like that; but I've also added some comments for the `LangCode` type in the generator file.

**Comment by humenda** [comment]
, N

**Comment by humenda** [comment]
Nice, thanks. Would you maybe also rewrite the history into 1-3 commits? Or should I squash them all together?

**Comment by djc** [comment]
Feel free to just squash them if you prefer that.

**Comment by djc** [comment]
Would be appreciated if you can publish another release with this!

**Comment by humenda** [comment]
>Would be appreciated if you can publish another release with this!

Makes sense, I'll do a 2.1 release.

Cheers
Sebastian

**Comment by djc** [comment]
Thanks, enjoy your holiday break!

**Comment by humenda** [comment]
Thanks, and thanks for all your help!

**Pull request merged**
