### PR TITLE
Alternative Serde implementation

### PR DESCRIPTION
**Pull request by tim-harding**
Using `serde_json` with this library, I was getting the following error during deserialization:

`Error: Error("invalid type: string \"eng\", expected a borrowed str", line: 235, column: 31)`

I found this had to do with the way the impl was done for this library. Without digging in too much, I would guess that `serde_json` is trying to pass an owned string rather than a borrowed one. I'm not sure if there are performance advantages to the current implementation, but for my own purposes, I switched to derive impl for the `Serialize` and `Deserialize` traits. The only difference to the serialized values is that the first letter is capitalized, as it is in the enum variants. It would be possible to add [`#[serde(rename_all = "lowercase")]`](https://serde.rs/container-attrs.html#rename_all) if this is undesirable. This implementation now works correctly with `serde_json`.

### CODE REVIEW

**Comment by tim-harding** [comment]
Upon further usage, one consequence of this I've discovered is quite bloated build times. Tested with `cargo bloat`, I was getting 42 seconds to build this crate before the change and 101 seconds after. I'll keep working on a better version of this PR to keep build times somewhat manageable.

**Comment by humenda** [comment]
Hi

>Upon further usage, one consequence of this I've discovered is quite bloated build times. Tested with `cargo bloat`, I was getting 42 seconds to build this crate before the change and 101 seconds after. I'll keep working on a better version of this PR to keep build times somewhat manageable. 

Thanks a lot for looking into this! Then I'll wait for your ping on this.

**Comment by humenda** [comment]
Hi

Have you been able to make progress on the build time issue that you've
experienced?

**Comment by tim-harding** [comment]
I haven't worked on it for a while. School's been busy and I've been focusing on my own project. If you'd like, we can close this out and I'll loop back around to it when I have bandwidth.

**Comment by humenda** [comment]
Ok, that is unfortunate to hear. Then I'll wait for your changes once you've got more time. Thanks!

**Pull request closed without merging**
