### PR TITLE
Feature - Add native names

### PR DESCRIPTION
**Pull request by zbrox**
This adds an additional function which returns (if available) the autonym (or the native language name) of a given language.

### CODE REVIEW

**Comment by humenda** [comment]
Hi

Thanks for your work!  
As for build.rs, I would prefer if you could refactor the Vec in `build.rs:12`
to hold a named struct with pub fields. It becomes hard to comprehend when we
keep extending the tuple.

Given the size of the English and local names, I would favour to feature-gate
this. Maybe `english_names` and `local_names`? What do you think? Would you be
willing to implement this?

**Comment by zbrox** [comment]
Yeah, this makes sense. I just didn't want to make assumptions and tried to fit into the current setup as much as possible.
I also didn't want to touch the existing API. I would guess that you'd prefer to keep the current to_name to return the English name?

**Comment by zbrox** [comment]
And yeah, I haven't used feature gates but I'll read up on it. And I'll try to implement this.

**Comment by humenda** [comment]
I would suggest feature-gating English names and local names separately. This
way the library could be used to convert between two-letter and three-letter
codes without the binary size bloat of the names. In this scenario,
`to_name()` would then be part of the `english_names` feature.
`english_names` should be a default feature that most people would expect, not
sure about the local names, your view?  
I'm fine with incompatible API. :)

**Comment by humenda** [comment]
Thanks, if you need help, please let me know (I'm on IRC as well).

**Comment by zbrox** [comment]
Yeah, now I understand what you mean, I was a bit too quick to respond maybe :) I guess the use case of needing to get both English and native names is probably pretty slim and can be changed later on. I will give implementing this a go and I'll push when I have something. Looking forward to comments. 

P.S. Which IRC server?

**Comment by zbrox** [comment]
Nevermind the IRC comment :) I just figured that out :)

**Comment by humenda** [comment]
https://github.com/humenda :)

**Comment by zbrox** [comment]
This is my first time doing conditional compilation in Rust, so hopefully, I got it ok. I was especially not certain about it when it comes to the rustdoc documentation blocks.

**Comment by humenda** [comment]
Hi

There are a few issues, would you be willing to work on these?

`build.rs`:

-   Instead of `LanguageName`, I had thought of `Language` as a struct, but I
    could change this as well.
-   `line`, could you use `language`?

`lib.rs`

-   Here's a slight misunderstanding, I'd like to keep `to_name` its behaviour
    and you should add, as previously, `to_autonym`. `to_name` is then
    `cfg(english_names)`. This way we actually keep API compatibility.j
-   You could have used `if cfg!` for the Display impl of Language, but that's
    not too bad ;).    

Thanks

**Comment by zbrox** [comment]
I'm sorry, my bad. I misunderstood. It makes more sense to be able to build this in a way that you can have access to both the English and local names or only the English names if needed.

I think I have addressed your latest comments. Please tell me if I have misunderstood something more and I'll change it accordingly.

**Comment by humenda** [comment]
I am really sorry, but I've been unattentive to the exact changes. Am I right
that you merged the `*.tab` file with the one that you reference in the comment?
If so I would argue it would be better to have both separately and to parse them
separately as well, because this way it's easier to merge in new upstream
versions. What do you think? How did you merge the two files?
The rest looks good!

**Comment by zbrox** [comment]
I understand the concern. I merged them manually with a script matching on the three letter codes. I have separated that out now and that is done on build time. This might be a bit slower on build time but I can't decide if that is a big consideration or not.

**Comment by zbrox** [comment]
I accidentally closed :) Wrong button

**Comment by humenda** [comment]
Thanks for your work! I extended the doc strings slightly and merged it. I'll
need to fix some breakage in the tests before I can make a release.

**Comment by zbrox** [comment]
No problem! I try running `cargo test` with both features in order to make sure current tests run. If I've broken something I can help out to fix it. I just hadn't noticed.

**Pull request merged**
