### PR TITLE
Setup CI using GitHub Actions

### PR DESCRIPTION
**Pull request by djc**
Travis support seems non-functional, and GitHub Actions is usually faster (and more popular).

### CODE REVIEW

**Comment by humenda** [comment]
What is the motivation to move away from travis? I'll merge it once I
understand your motivation of not using Travis.

**Comment by djc** [comment]
1. Travis currently doesn't seem to be working for this repo
2. Travis is much slower than GitHub Actions
3. Travis was acquired two years ago and since then it has had mishandled security issues (https://news.ycombinator.com/item?id=28524727), is no longer providing credits to OSS projects (https://news.ycombinator.com/item?id=25338983), https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works.

**Comment by humenda** [comment]
Ok, thanks for your reasoning.

I am going to do the 2.0.0 release tomorrow if you do not have anything else that
you would like to see in the next release.

**Comment by djc** [comment]
Would still like to have #23, but otherwise having the 2.0 release sounds good!

**Comment by humenda** [comment]
I was following the link  in the README to the build status though it leads me
to a page where I can create a new GitHub action. It seems you didn't set it
up yet. Would be you willing to do this?

**Comment by djc** [comment]
I would, but I don't think I can -- typically as a collaborator you don't have access to the settings for a repository residing in a personal account. If you go to Settings -> Actions tab I think you can enable it there.

**Comment by humenda** [comment]
>If you go to Settings -> Actions tab I think you can enable it there.

I have never used GitHub actions, but from the selected settings I conclude
that you as a colaborator can run workflows when I approve it the first time.
What a workflow is and how you would initiate it, I cannot tell.

**Pull request merged**
